services:
  uw:
    # Name of the container
    container_name: uw

    # Build image from Dockerfile
    build: ./university-whatsapp

    # Environment variables
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
